# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: Minh To

# A description of your site for social meta tag, search engines, and feed.xml
description: Just a normal day

# The base hostname & protocol of your site for where absolute urls are needed
url: https://tsminh.github.io

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
    sass_dir: _sass

navigation:
    - text: Dev diary
      url: /dev
    - text: Travel
      url: /travel
    - text: About
      url: /about
    - text: Archives
      url: /travel/tags

# Author information - author info at the bottom of the post
author_name: "Hieu-Minh To"
author_bio: ""
author_url: "https://tsminh.github.io"
author_location: "VN"
author_image: authorimage.jpg

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: "/blog/page:num/"
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
